source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'
gem 'mqtt', '~> 0.4.0'
gem 'rails', '~> 6.1.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_bot_rails', '~> 6.1'
  gem 'pp', '~> 0.2.0'
  gem 'rspec-rails', '~> 4.0', '>= 4.0.2'
end

group :development do
  gem 'annotate', '~> 3.1', '>= 3.1.1'
  gem 'brakeman', '~> 5.0'
  gem 'bullet', '~> 6.1', '>= 6.1.3'
  gem 'listen', '~> 3.3'
  gem 'rails-flog', '~> 1.6', '>= 1.6.1'
  gem 'reek', '~> 6.0', '>= 6.0.3'
  gem 'rubocop', '~> 1.9', '>= 1.9.1'
  gem 'shoulda-matchers', '~> 4.5', '>= 4.5.1'
  gem 'sorbet', '~> 0.5.6281'
  gem 'spring', '~> 2.1', '>= 2.1.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
