version: "3.9"
services:
  dev_env:
    container_name: dev_env
    build:
      context: ${DEV_DIRECTORY}
      target: local
    volumes:
      - ${RAILS_ROOT_DIRECTORY}:/projects/web_activity
      - ${ELIXIR_ROOT_DIRECTORY}:/projects/web_reports
    environment:
      TERM: xterm256-color

  db:
    container_name: ha_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${TEST_DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust

  web_activity:
    # image: ha_api_web:${IMAGE_TAG}
    container_name: ha_api_rails
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    build:
      context: ${RAILS_ROOT_DIRECTORY}
      target: local
    environment:
      RAILS_ENV: ${SYSTEM_ENV}
      MQTT_HOST: mosquitto
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ha_db
      DATABASE_NAME: ${DATABASE_NAME}
      TEST_DATABASE_NAME: ${TEST_DATABASE_NAME}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - ${RAILS_PORT}:3000
    volumes:
      - ${RAILS_ROOT_DIRECTORY}:/usr/src/app
    depends_on:
      - db

  mosquitto:
    container_name: ha_mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ${MQTT_ROOT_DIRECTORY}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  web_reports:
    container_name: ha_api_elixer
    build:
      context: ${ELIXIR_ROOT_DIRECTORY}
      target: local
    depends_on:
      - db
    environment:
      MIX_ENV: ${MIX_ENV}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      TEST_DATABASE_NAME: ${TEST_DATABASE_NAME}

    ports:
      - ${ELIXIR_PORT}:4000
    volumes:
      - ${ELIXIR_ROOT_DIRECTORY}:/usr/src/app


